# Supabase local development configuration
project_id = "supabase-ui-svelte"

[api]
enabled = true
port = 54321

[db]
port = 54322
major_version = 15

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[auth]
enabled = true
site_url = "http://localhost:5173"
enable_signup = true

[auth.mfa.totp]
enroll_enabled = true
verify_enabled = true


[auth.email]
enable_signup = true
enable_confirmations = true